name: Auto Label PR

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, edited, reopened, synchronize ]

jobs:
  label-plugin-pr:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Auto Apply Labels
        uses: srvaroa/labeler@master
        with:
          config_path: .github/pr-labeler-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
